[package]
name = "publication-evaluation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
adapter-simulated-asset = { path = "../adapter-simulated-asset" }
adapter-sqlite-asset = { path = "../adapter-sqlite-asset" }
base64.workspace = true
ed25519-dalek.workspace = true
hete-adapter-api = { path = "../hete-adapter-api" }
hete-credential = { path = "../hete-credential" }
hete-identity = { path = "../hete-identity" }
hete-policy = { path = "../hete-policy" }
libc.workspace = true
poa-protocol = { path = "../poa-protocol" }
serde_json.workspace = true
sha2.workspace = true
